### PR TITLE
Primary relationships fixes

### PR DESCRIPTION
**Pull request by cli0**
Fixed the project path, the naming of the tables, new lines and some other details.

### CODE REVIEW

**Comment by webstergd** [comment]
the configuration should be moved to /config to make it consistent. Additionally, config files should always have a .example at the end to help ensure private data doesn't get captured in a pull and the repo can be updated if the files is ever adjusted. take a look at https://github.com/HolmesProcessing/Holmes-Analytics for an example

**Comment by webstergd** [comment]
Everything else looks good but I am still curious on the scheme. We can look at it again after GSoC..Anyway, good work, please correct the config and then lets more forward!

**Comment by cli0** [comment]
About the scheme and everything. I will explain the workflow in the documentation/blog post. Or do you need me to provide that as soon as possible regardless of the blog?

**Comment by webstergd** [comment]
Don't worry. I am following what you are doing. That was a note for after gsoc. Just move forward.

**Pull request merged**
